In [1]:
import numpy as np

In [4]:
#EX1
n = int(input("Enter length"))
a = []
for i in range(1,n+1):
    a.append(i)
b = np.array(a)
arr = np.diag(b)
print(arr)


Enter length5
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [62]:
import time 
#EX2
start = time.time()
n = int(input("Enter length"))
arr = np.full((n,n),0)
arr[0:n:2 , 1:n:2] = 1
arr[1::2 , 0:n:2] = 1

stop = time.time()
print(f"Execution_Time:{(stop-start)}sec")

print(arr , "\n\n")



start = time.time()

arr2 = [[0 for i in range(n)] for i in range(n)]


for i in range(len(arr2)):
    if i %2 == 0:
        for j in range(1 ,len(arr2) , 2):
                arr2[j] = 1
    if i %2 != 0: 
        for j in range(0 ,len(arr2) , 2):
                arr2[j] = 1
stop = time.time()
print(f"Execution_Time:{(stop-start)}sec")
print(arr)

Enter length5
Execution_Time:1.139014720916748sec
[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]] 


Execution_Time:0.0009996891021728516sec
[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


##### 

In [81]:
#Ex3
n = int(input("Enter n"))
m = int(input("Enter m"))
r = int(input("Enter r"))
c = int(input("Enter c"))
arr = np.full((n,m),1)
arr[0:n:r , 0:m:1] = 0
arr[0:n:1 , 0:m:c] = 0
print(arr)

Enter n5
Enter m5
Enter r2
Enter c2
[[0 0 0 0 0]
 [0 1 0 1 0]
 [0 0 0 0 0]
 [0 1 0 1 0]
 [0 0 0 0 0]]


In [18]:
#Ex4
n = int(input("Enter n"))
m = int(input("Enter m"))
arr=np.full((m,n),0)
x = np.arange(m-1)
arr[0] =  x
print(arr)

Enter n3
Enter m4
[[0 1 2]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


### 

In [16]:
#Ex6
n = int(input("Enter count of rows"))
a = []
for i in range(n):
    col = int(input("Enter elements "))
    if col !=0:
        col = -1
    a.append(col)
arr = np.array(a)
print(arr)

        
     

Enter count of rows7
Enter elements 9
Enter elements 0
Enter elements -1
Enter elements 4
Enter elements 5
Enter elements 0
Enter elements 2
[-1  0 -1 -1 -1  0 -1]


In [17]:
#Ex8
n = int(input("Enter count of rows"))
a = []
countOfNulls = 0
countOfNotNulls = 0
for i in range(n):
    col = int(input("Enter elements "))
    if col == 0:
        countOfNulls+=1
    if col !=0:
        countOfNotNulls+=1
    a.append(col)
arr = np.array(a)
print(arr)
print("Count of Nulls: " , countOfNulls , "\ncountOfNotNulls: " ,countOfNotNulls )


Enter count of rows5
Enter elements 2
Enter elements 0
Enter elements 8
Enter elements 1
Enter elements 5
[2 0 8 1 5]
Count of Nulls:  1 
countOfNotNulls:  4


In [15]:
#Ex11
n = int(input("Enter length"))
arr = np.full((n,n),1)
arr[0:n:n-1 , 0:n:1] = 0
arr[1:n-1:1 , 0:n:n-1] = 0
print(arr)

KeyboardInterrupt: Interrupted by user

In [16]:
#Ex20
n = int(input("Enter count of elements in vector"))
v = np.random.random(n)
i = np.argmax(v)
print(v)
v[i] = 0
print("Changed array = " ,v)

Enter count of elements in vector2
[0.52613373 0.77122831]
Changed array =  [0.52613373 0.        ]


In [17]:
#Ex21
n = int(input("Enter n"))
m = int(input("Enter m"))
arr = np.random.randint(0,m ,(n,n))
print(arr)
max_num = np.max(arr)
for i in range(len(arr)):
    for j in range(len(arr)):
        if arr[i , j] == max_num:
            arr[i , j]*=-1
print(arr)
np.allclose(v , arr)

        





Enter n4
Enter m10
[[3 2 0 9]
 [9 2 4 7]
 [6 4 1 0]
 [8 0 6 7]]
[[ 3  2  0 -9]
 [-9  2  4  7]
 [ 6  4  1  0]
 [ 8  0  6  7]]


ValueError: operands could not be broadcast together with shapes (2,) (4,4) 

# 

In [53]:
#Завдання 3 - матриці 3(A^2-B^2)-2AB
import time

start = time.time()


A = np.array([[4 , 2, 1],
              [3 ,-2 ,0],
              [0 , 1,2]])

B = np.array([[2,0,2],
              [5,-7,-2],
              [1,0,-1]])

result = 3*(A@A - B@B)- 2* A@B
stop = time.time()
print(f"Execution_Time:{(stop-start)}sec")
print(result)

Execution_Time:0.0sec
[[  10   43    6]
 [ 107 -145  -89]
 [  -8   14   11]]


In [51]:
#Завдання 3 - матриці(2 спосіб) 3(A^2-B^2)-2AB
import time

start = time.time()


A = [[4,2,1] ,[3,-2,0] ,[0,1,2]]
B = [[2,0,2] ,[5,-7,-2] ,[1,0,-1]]
step1 = [[0 for i in range(len(A))] for i in range(len(A))]
step2 =[[0 for i in range(len(A))] for i in range(len(A))]
step3= [[0 for i in range(len(A))] for i in range(len(A))]
step4= [[0 for i in range(len(A))] for i in range(len(A))]
step5= [[0 for i in range(len(A))] for i in range(len(A))]
step6= [[0 for i in range(len(A))] for i in range(len(A))]
step7= [[0 for i in range(len(A))] for i in range(len(A))]


for i in range(len(A)):
    for j in range (len(A[i])):
        step1[i][j] = 0
        for z in range(len(A[j])):
             step1[i][j] += A[i][z] * A[z][j]    
 




for i in range(len(B)):
    for j in range (len(B[i])):
        step2[i][j] = 0
        for z in range(len(B[j])):
             step2[i][j] += B[i][z] * B[z][j]    
             
for i in range(len(B)):
    for j in range (len(B[i])):
        step3[i][j] += step1[i][j] - step2[i][j]
            
for i in range(len(B)):
    for j in range (len(B[i])):
        step4[i][j] += 3 *  step3[i][j]
            
for i in range(len(B)):
    for j in range (len(B[i])):
        step5[i][j] = 0
        for z in range(len(B[j])):
             step5[i][j] += A[i][z] * B[z][j]     

for i in range(len(B)):
    for j in range (len(B[i])):
        step6[i][j] += -2 *  step5[i][j]
                 
for i in range(len(B)):
    for j in range (len(B[i])):
        step7[i][j] += step4[i][j] + step6[i][j]
stop = time.time()
print(f"Execution_Time:{(stop-start)}sec")
print(step7)




Execution_Time:0.0009982585906982422sec
[[10, 43, 6], [107, -145, -89], [-8, 14, 11]]


In [12]:
#Завдання 2 
a = np.array([[4 , 1 , 0 , -1], [1 , -3 , 4 , 0] , [0 , 3 , -2 , 4] , [1 , 0 , 2 , 4]])
b = np.array([-9 , 7 , 12 , 12 ])
"""First method"""
x = np.linalg.solve(a ,b )

"""Second method"""
matrix = np.linalg.inv(a)
x2 = np.matmul(matrix , b)

np.allclose(x , x2)

[-1.49028206e+16  4.47084618e+16  3.72570515e+16 -1.49028206e+16]


NameError: name 'x' is not defined